export default {
  rus: {
    support: 'Поддержка',
    langSelect: 'Язык: ',
    lang: 'Русский',
    themeTitle: 'Тема:',
    loginAuth: 'Войдите в аккаунт',
    loginAuthBtn: 'Войти',
    loginAuthForgot: 'Забыли пароль?',
    enterEmail: 'Введите Email',
    correctEmail: 'Введите корректный Email',
    passLogin: 'Пароль',
    passLoginEnter: 'Введите пароль',
    validatePass1: 'Пароль должен быть не менее',
    validatePass2: 'символов. Сейчас он',
    passInfo: 'Пароль должен состоять из латинских букв, цифр и знаков. Обязательно содержать одну заглавную букву, одну цифру и состоять из 8 символов.',
    passLevelFirst: 'слабый',
    passLevelSecond: 'средний',
    passLevelTree: 'надёжный',
    repeatPassword: 'Повторите пароль',
    matchPassword: 'Пароли должны совпадать',
    createAccTitle: 'Создание аккаунта',
    createAccStepBtn: 'Дальше',
    createAccPersonalTitle: 'Личные данные',
    createAccCaptchaDescr: 'Введите символы, которые вы видите на экране',
    createAccCaptchaRefresh: 'Обновить',
    createAccBtnReg: 'Зарегистрироваться',
    createAccBtnBack: 'Назад',
    createAccNameField1: 'Имя',
    createAccNameField2: 'Фамилия',
    requiredField: 'Обязательное поле',
    minimumNumberOfCharacters: 'Минимальное количество символов',
    codeTitle: 'Код',
    codeNoMatch: 'код не совпадает',
    confirmComponent1: 'Я согласен с ',
    confirmComponent2: 'полит. конф-ти',
    confirmComponent3: ' и передачей ',
    confirmComponent4: 'перс. данных',
    recoveryPassTitle: 'Восстановление пароля',
    recoveryPassDescription: 'Укажите, куда отправить инструкции для восстановления пароля.',
    recoveryPassBtn: 'Отправить',
    setNewPasswordTitle: 'Новый пароль',

    sidebarMyPage: 'Моя страница',
    sidebarFriend: 'Друзья',
    sidebarMessage: 'Сообщения',
    sidebarNews: 'Новости',
    sidebarSetting: 'Настройки',

    yes: 'Да',
    cancel: 'Отмена',

    registerSucces: 'Успешно!',
    searchPlaceholder: 'Поиск',
    logout: 'Выйти',

    notNotification: 'Уведомлений нет',
    showmoreNotification: 'Показать еще',
    readedNotification: 'Отметить всё как прочитанное',

    recommendBlockTitle: 'Возможно вы их знаете',
    recommendBlockDescription: 'В данный момент нет вариантов. Для получения рекомендаций, добавьте несколько друзей.',
    recommendBlockBtn: 'Искать друзей',
    recommendBlockAdd: 'Добавить',

    profileSharedAccTitle: 'Поделиться:',
    profileMyPublishText: 'Мои публикации',
    profileMyPublishNoMe: 'Публикации',
    profileNotFilled: 'не заполнено',
    profileNotFilledAll: 'профиль не заполнен',
    profileEditingText: 'Редактировать профиль',
    profileActionsUser: 'Действия',
    profileAccountUnsubscribe: 'Отписаться',
    profileAccountSubscribe: 'Подписаться',
    profileAccountAcceptRequests: 'Принять запрос',
    profileAccountSendMessage: 'Написать сообщение',
    profileAccountUnblocking: 'Разблокировать',
    profileAccountBlocking: 'Заблокировать',
    profileAccountDeleteFriend: 'Удалить из друзей',
    profileAccountCancelFriend: 'Отменить заявку',
    profileAccountAddFriend: 'Добавить в друзья',
    profileInfoBirthday: 'Дата рождения:',
    profileInfoPhone: 'Телефон:',
    profileInfoCountry: 'Страна, город:',
    profileInfoAbout: 'О себе:',
    profileInfoStatusOnline: 'онлайн',
    profileInfoStatusOffline: 'оффлайн',

    profileBlockMyPublished: 'Опубликованные',
    profileBlockMyQueued: 'Запланированные',

    weatherHumidity: 'Влажность',
    weatherWind: 'Ветер',
    weatherMinTemp: 'Мин. температура:',
    weatherMaxTemp: 'Макс. температура:',
    weatherLoading: 'Загружаем данные с погодой...',

    friendsTitle: 'Мои друзья',
    friendsSearchPlaceholder: 'Начните вводить имя друга...',
    friendsRequestsFrom: 'Запросы в друзья',
    friendsRequestsTo: 'Исходящие запросы',
    friendsMySubscribe: 'Подписчики',
    friendsBlocked: 'Заблокированные',
    friendsMyPesonalSubscribed: 'Подписан(а)',
    friendsSearchResultClear: 'Сбросить',
    friendsSearchDescription: 'Результаты поиска по запросу',
    friendsShowMore: 'Загрузить ещё...',
    friendsNoResult: 'Вы никому не отправляли заявку в друзья,' +
    ' самое время начать общаться.',
    friendsNoActiveTab: 'Выберите одну из доступных вкладок c друзьями.',

    friendsBlockEdit: 'Редактировать',
    friendsBlockDelete: 'Удалить из списка',

    friendsModalLastText: ' из друзей?',
    friendsModalLastTextSecond: ' из списка модераторов?',
    friendsModalTextDelete: 'Вы уверены, что хотите удалить пользователя ',
    friendsModalTextDeleteSub: 'Вы уверены, что хотите отписаться от пользователя ',
    friendsModalTextCancelFriend: 'Вы уверены, что хотите отменить запрос в дружбу с ',
    friendsModalTextDeteleModerator: 'Вы уверены, что хотите удалить ',
    friendsModalTextBlocked: 'Вы уверены, что хотите заблокировать пользователя ',
    friendsModalTextUnlock: 'Вы уверены, что хотите разблокировать пользователя ',

    friendsFindTitle: 'Найти друзей',
    friendsFindFindFirstText: 'Найдено',
    friendsFindFindSecondText: 'человек',

    friendsFindParamsTitle: 'Параметры поиска',
    friendsFindYearTitle: 'Возраст:',
    friendsFindFrom: 'От',
    friendsFindTo: 'До',
    friendsFindRegion: 'Регион:',
    friendsFindCountry: 'Страна',
    friendsFindCity: 'Город',
    friendsFindCheckbox: 'Поиск по всем пользователям',

    newsAddPlaceholder: 'Поделитесь новостью...',
    newsAddTitle: 'Дайте тему',
    newsAddSettings: 'Настройка публикации',
    newsAddSettingsTimePublished: 'Запланированное время',
    newsAddQueued: 'Запланировать',
    newsAddPosted: 'Опубликовать',
    newsAddQueuedTimeToPosted: 'Публикация будет опубликована:',
    newsAddDataPickedData: 'Выберите дату',
    newsAddDataPickedTime: 'Выберите время',

    newsTagPlaceholder: 'Начните вводить...',

    newsBlockPublishedTitle: 'опубликован',
    newsBlockEditedTime: 'изменен',
    newsBlockDeleted: 'Удалить',
    newsBlockQueuedTime: 'Дата и время публикации:',
    newsBlockQueuedDatatime: 'будет опубликован',
    newsBlockReadedMore: 'Читать далее',
    newsBlockReadedHide: 'Скрыть',
    newsBlockReadedTime: 'мин.',
    newsBlockReadedDisclamer: 'Примерно столько времени вы потратите на прочтение этой статьи',
    newsBlockCommentTitleFirst: 'Посмотреть комментарии',
    newsBlockCommentTitleSecond: 'Скрыть комментарии',
    newsBlockCommentMore: 'Ещё комментарии...',

    commentAddPlaceholderFirst: 'Написать ответ...',
    commentAddPlaceholderSecond: 'Написать комментарий...',
    commentAnswerShow: 'показать',
    commentAnswerTextFirst: 'ответа',
    commentAnswerTextSecond: 'ответ',
    commentIsDeleted: 'Комментарий удален.',
    commentIsRecovery: 'Восстановить',
    commentAddAnswer: 'Ответить',

    searchNewsAuthor: 'Автор:',
    searchNewsInputPlaceholder: 'Введите автора',
    searchNewsTimePost: 'Время публикации:',
    searchNewsAllTime: 'За все время',
    searchNewsLastYear: 'За последний год',
    searchNewsLastMonth: 'За последний месяц',
    searchNewsLastWeek: 'За последнюю неделю',
    searchNewsBtnComplited: 'Применить',

    searchUserNameInput: 'Введите имя',
    searchUserSurnameInput: 'Введите фамилию',
    searchUserTitle: 'Люди',
    searchNewsTitle: 'Новости',
    searchNewsEmpty: 'В данный момент нет новостей для отображения',
    searchUserEmpty: 'В данный момент нет людей для отображения',

    settingBtnChange: 'Изменить',
    settingPasswordLabel: 'Пароль:',
    settingPasswordPlaceholder: 'Введите текущий пароль',
    settingPasswordPlaceholder2: 'Введите новый пароль',

    settingsMainAddCover: 'Добавить обложку',
    settingsMainEditCover: 'Изменить обложку',
    settingsMainEditPhoto: 'Изменить фото',
    settingMainAddPhoto: 'Добавить фото',
    settingMainPhotoAlt: 'Нет фото',
    settingMainPlaceholderPhone: 'Введите телефон',
    settingMainPlaceholderCountry: 'Выберите страну',
    settingMainPlaceholderCity: 'Выберите город',
    settingMainCountry: 'Страна:',
    settingMainCity: 'Город:',
    settingMainUnknow: 'Неизвестно',
    settingMainAbout: 'О себе:',
    settingMainSave: 'Сохранить',
    settingMainCancel: 'Отменить',

    settingDeleteTitle: 'После удаления профиля будет удалена вся связанная с ним информация: друзья, публикации, комментарии, лайки.',
    settingDeleteLabel: 'Да, удалить мою страницу и всю связанную с ней информацию',
    settingDeleteButton: 'Удалить профиль',
    settingDeleteCancel: 'Не удалять профиль, я хочу вернуться',

    settingModalEmailChange: 'Адрес электронной почты успешно изменен на',
    settingModalPasswordChange: 'Пароль успешно изменен'
  },

  eng: {
    support: 'Support',
    langSelect: 'Language: ',
    lang: 'English',
    themeTitle: 'Theme:',
    loginAuth: 'Log in to your account',
    loginAuthBtn: 'Log in',
    loginAuthForgot: 'Forgot your password?',
    enterEmail: 'Enter Email',
    correctEmail: 'Enter the correct Email',
    passLogin: 'Password',
    passLoginEnter: 'Enter the password',
    validatePass1: 'The password must be at least',
    validatePass2: 'characters. Now he',
    passInfo: 'The password must consist of Latin letters, numbers and signs. It must contain one capital letter, one digit and consist of 8 characters.',
    passLevelFirst: 'weak',
    passLevelSecond: 'average',
    passLevelTree: 'reliable',
    repeatPassword: 'Repeat the password',
    matchPassword: 'Passwords must match',
    createAccTitle: 'Creating an account',
    createAccStepBtn: 'Next',
    createAccPersonalTitle: 'Personal data',
    createAccCaptchaDescr: 'Enter the characters you see on the screen',
    createAccCaptchaRefresh: 'Update',
    createAccBtnReg: 'Register',
    createAccBtnBack: 'Back',
    createAccNameField1: 'Name',
    createAccNameField2: 'Surname',
    requiredField: 'Required field',
    minimumNumberOfCharacters: 'Minimum number of characters',
    codeTitle: 'Code',
    codeNoMatch: 'the code doesnt match',
    confirmComponent1: 'I agree with ',
    confirmComponent2: 'privacy policy',
    confirmComponent3: ' and transfer ',
    confirmComponent4: 'personal data',
    recoveryPassTitle: 'Password recovery',
    recoveryPassDescription: 'Specify where to send instructions for password recovery.',
    recoveryPassBtn: 'Send',
    setNewPasswordTitle: 'New password',
    sidebarMyPage: 'My page',
    sidebarFriend: 'Friends',
    sidebarMessage: 'Messages',
    sidebarNews: 'News',
    sidebarSetting: 'Settings',
    registerSucces: 'Successfully!',
    searchPlaceholder: 'Search',
    logout: 'Exit',

    notNotification: 'There are no notifications',
    showmoreNotification: 'Show more',
    readedNotification: 'Mark everything as read',

    recommendBlockTitle: 'Perhaps you know them',
    recommendBlockDescription: 'There are no options at the moment. To get recommendations, add a few friends.',
    recommendBlockBtn: 'Search for friends',
    recommendBlockAdd: 'Add',

    profileSharedAccTitle: 'To share:',
    profileMyPublishText: 'My publications',
    profileMyPublishNoMe: 'Publications',
    profileNotFilled: 'empty',
    profileNotFilledAll: 'profile is not filled',
    profileEditingText: 'Edit profile',
    profileActionsUser: 'Actions',
    profileAccountUnsubscribe: 'Unsubscribe',
    profileAccountSubscribe: 'Subscribe',
    profileAccountAcceptRequests: 'Accept the request',
    profileAccountSendMessage: 'Write a message',
    profileAccountUnblocking: 'Unlock',
    profileAccountBlocking: 'Block',
    profileAccountDeleteFriend: 'Remove from friends',
    profileAccountCancelFriend: 'Cancel the application',
    profileAccountAddFriend: 'Add to friends',
    profileInfoBirthday: 'Date of birth:',
    profileInfoPhone: 'Phone:',
    profileInfoCountry: 'Country, city:',
    profileInfoAbout: 'About me:',
    profileInfoStatusOnline: 'online',
    profileInfoStatusOffline: 'offline',
    profileBlockMyPublished: 'Published',
    profileBlockMyQueued: 'Planned',

    weatherHumidity: 'Humidity',
    weatherWind: 'Wind',
    weatherMinTemp: 'Min. temperature:',
    weatherMaxTemp: 'Max. temperature:',
    weatherLoading: 'Uploading weather data...',

    yes: 'Yes',
    cancel: 'Cancel',

    friendsTitle: 'My friends',
    friendsSearchPlaceholder: `Start typing a friend's name...`,
    friendsRequestsFrom: 'Friend requests',
    friendsRequestsTo: 'Outgoing requests',
    friendsMySubscribe: 'Subscribers',
    friendsBlocked: 'Blocked',
    friendsMyPesonalSubscribed: 'Signed',
    friendsSearchResultClear: 'Reset',
    friendsSearchDescription: 'Search results for',
    friendsShowMore: 'Show more...',
    friendsNoResult: 'You have not sent a friend request to anyone,' +
    ` it's time to start communicating.`,
    friendsNoActiveTab: 'Select one of the available tabs with friends.',
    friendsBlockEdit: 'Edit',
    friendsBlockDelete: 'Remove from the list',

    friendsModalLastText: ' from friends?',
    friendsModalLastTextSecond: ' from the list of moderators?',
    friendsModalTextDelete: 'Are you sure you want to delete the user ',
    friendsModalTextDeleteSub: 'Are you sure you want to unsubscribe from the user ',
    friendsModalTextCancelFriend: 'Are you sure you want to cancel the friendship request with ',
    friendsModalTextDeteleModerator: 'Are you sure you want to delete ',
    friendsModalTextBlocked: 'Are you sure you want to block the user ',
    friendsModalTextUnlock: 'Are you sure you want to unblock the user ',

    friendsFindTitle: 'Find friends',
    friendsFindFindFirstText: 'Found',
    friendsFindFindSecondText: 'human',

    friendsFindParamsTitle: 'Search parameters',
    friendsFindYearTitle: 'Age:',
    friendsFindFrom: 'From',
    friendsFindTo: 'To',
    friendsFindRegion: 'Region:',
    friendsFindCountry: 'Contry',
    friendsFindCity: 'City',
    friendsFindCheckbox: 'Search by all users',

    newsAddPlaceholder: 'Share the news...',
    newsAddTitle: 'Give me a topic',
    newsAddSettings: 'Setting up a publication',
    newsAddSettingsTimePublished: 'Scheduled time',
    newsAddQueued: 'Schedule',
    newsAddPosted: 'To publish',
    newsAddQueuedTimeToPosted: 'The publication will be published:',
    newsAddDataPickedData: 'Select a date',
    newsAddDataPickedTime: 'Choose a time',
    newsTagPlaceholder: 'Start typing...',

    newsBlockPublishedTitle: 'published',
    newsBlockEditedTime: 'changed',
    newsBlockQueuedTime: 'Date and time of publication:',
    newsBlockDeleted: 'Deleted',
    newsBlockQueuedDatatime: 'will be published',
    newsBlockReadedMore: 'Read more',
    newsBlockReadedHide: 'Hide',
    newsBlockReadedTime: 'min.',
    newsBlockReadedDisclamer: `That's about the amount of time you'll spend reading this article`,
    newsBlockCommentTitleFirst: 'View comments',
    newsBlockCommentTitleSecond: 'Hide comments',
    newsBlockCommentMore: 'More comments...',

    commentAddPlaceholderFirst: 'Write an answer...',
    commentAddPlaceholderSecond: 'Write a comment...',
    commentAnswerShow: 'show',
    commentAnswerTextFirst: 'replies',
    commentAnswerTextSecond: 'answer',
    commentIsDeleted: 'The comment has been deleted.',
    commentIsRecovery: 'Recover',
    commentAddAnswer: 'Reply',

    searchNewsAuthor: 'Author:',
    searchNewsInputPlaceholder: 'Enter the author',
    searchNewsTimePost: 'Publication time:',
    searchNewsAllTime: 'For all the time',
    searchNewsLastYear: 'For the last year',
    searchNewsLastMonth: 'For the last month',
    searchNewsLastWeek: 'For the last week',
    searchNewsBtnComplited: 'Apply',
    searchUserNameInput: 'Enter a name',
    searchUserSurnameInput: 'Enter your last name',
    searchUserTitle: 'People',
    searchNewsTitle: 'News',
    searchNewsEmpty: 'There is no news to display at the moment',
    searchUserEmpty: 'There are no people to display at the moment',

    settingBtnChange: 'Change',
    settingPasswordLabel: 'Password:',
    settingPasswordPlaceholder: 'Enter the current password',
    settingPasswordPlaceholder2: 'Enter a new password',

    settingsMainAddCover: 'Add a cover',
    settingsMainEditCover: 'Change the cover',
    settingsMainEditPhoto: 'Edit photo',
    settingMainAddPhoto: 'Add a photo',
    settingMainPhotoAlt: 'No photo',
    settingMainPlaceholderPhone: 'Enter your phone number',
    settingMainPlaceholderCountry: 'Select a country',
    settingMainPlaceholderCity: 'Choose a city',
    settingMainCountry: 'A country:',
    settingMainCity: 'City:',
    settingMainUnknow: 'Unknown',
    settingMainAbout: 'About me:',
    settingMainSave: 'Save',
    settingMainCancel: 'Cancel',

    settingDeleteTitle: 'After deleting a profile, all related information will be deleted: friends, posts, comments, likes.',
    settingDeleteLabel: 'Yes, delete my page and all related information',
    settingDeleteButton: 'Delete profile',
    settingDeleteCancel: `Don't delete the profile, I want to go back`,

    settingModalEmailChange: 'The email address has been successfully changed to',
    settingModalPasswordChange: 'Password changed successfully'
  },
}
